---
name: Container

on:
    push:
      branches: [ "main" ]
      paths:
        ['Dockerfile', 'requirements.txt', 'app/**', '.github/workflows/container-merge.yml']

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up QEMU
            uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
                
          - name: Build and push
            uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
            with:
                push: true
                tags: jackseceng/linkshort:latest
                provenance: true
                sbom: true
        
    analyze:
        runs-on: ubuntu-latest
        needs: build

        permissions:
            contents: read
            security-events: write

        steps:
          - name: Perform Grype Vulnerability Scan
            uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0
            id: grype-scan
            with:
                image: docker.io/jackseceng/linkshort
                fail-build: true
                severity-cutoff: medium
                only-fixed: true

          - name: Perform Scout Vulnerability Scan
            id: scout-scan
            uses: docker/scout-action@d341d36d6eebbe05c0b25760c63afa19e8f23269 # v1.17.0
            with:
                command: cves
                image: jackseceng/linkshort:latest
                ignore-unchanged: true
                only-severities: critical,high,medium
                write-comment: true
                github-token: ${{ secrets.GITHUB_TOKEN }}
                sarif-file: sarif.output.json
                summary: true
    
          - name: Upload scout result to GitHub Code Scanning
            uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
            with:
                sarif_file: sarif.output.json

          - name: Upload grype result to GitHub Code Scanning
            uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
            with:
                sarif_file: ${{ steps.grype-scan.outputs.sarif }}
