---
name: PR Checks

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

permissions:
  security-events: write
  packages: read
  actions: read
  contents: read
  artifact-metadata: read
  attestations: read
  deployments: read
  discussions: read
  id-token: read
  issues: read
  models: read
  pages: read
  repository-projects: read
  checks: read
  pull-requests: read
  statuses: read

jobs:
  code:
    uses: ./.github/workflows/codeql.yml

  semgrep:
    uses: ./.github/workflows/semgrep.yml
    secrets: inherit

  container:
    uses: ./.github/workflows/container.yml
    secrets: inherit
